[workspace]
members = [
    "crates/ardosia-network",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.98"

[workspace.dependencies]
bytes = "1.8"
thiserror = "2.0"
tokio = { version = "1.48", features = ["macros", "rt-multi-thread", "net", "sync", "time", "signal", "process", "io-util", "io-std", "fs"] }
raknet-rust = { git = "https://github.com/ardosia/ardosia-raknet", rev = "5db2b9373104c51f7582b4ca9e546b8d4384417a" }
